package projectManagement.entities;

public enum Action {
    CREATE_ITEM,
    DELETE_ITEM,
    CHANGE_ITEM_ASSIGN_TO_USER,
    CHANGE_ITEM_TYPE,
    CHANGE_ITEM_DESCRIPTION,
    ADD_COMMENT,
    DELETE_COMMENT,
    UPDATE_IMPORTANCE,
    CREATE_SUB_ITEM,
    ADD_STATUS,
    REMOVE_STATUS,
    ADD_TYPE,
    REMOVE_TYPE,
    ASSIGN_ROLE_TO_USER,
    CHANGE_ITEM_STATUS;
}
